name: Terragrunt Preview

on:
  pull_request:
    branches: [ main ]

jobs:
  terragrunt-plan:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Set up Terraform & Terragrunt
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Install Terragrunt
        run: |
          TG_VERSION=0.66.6
          curl -Lo terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      # Cache plugins to speed up runs
      - name: Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-plugins-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}

      # Plan all modules
      - name: Run Terragrunt Plan
        run: |
          mkdir -p terragrunt-plans
          terragrunt run-all plan --out=plan.tfplan || true
          find . -type f -name plan.tfplan | while read plan; do
              dir_name=$(dirname "$plan" | sed 's#.*/##')
              terragrunt show "$plan" > "terragrunt-plans/${dir_name}.plan.txt"
          done

      # Upload plan artifacts for manual review
      - name: Upload plan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terragrunt-plans
          path: terragrunt-plans/

      # Post comment to PR
      - name: Comment PR with plan summary
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: terragrunt-plan
          message: |
            ## 🌱 Terragrunt Plan Summary
            Plans for each module are available as build artifacts.
            ```diff
            $(grep -h -E "Plan:|Destroy" terragrunt-plans/*.plan.txt || echo "No changes detected.")
            ```